<a href="https://colab.research.google.com/github/NishanRegmi/Pytorch/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
if torch.cuda.is_available():
  print("GPU is using")
  print(f"GPU model {torch.device('cuda')}")
else:
  print("CPU is working")

GPU is using
GPU model cuda


In [ ]:
"""
autograd is a core component of PyTorch that provides automatic differentiation for tensor operations. It enables gradient computation, which is
essential for training machine learning and deep learning models using optimization algorithms like gradient descent.
"""
#computing gradinet using pytorch
x = torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [ ]:
y = x ** 2
y

tensor(25., grad_fn=<PowBackward0>)

In [ ]:
y.backward() #tracking back

In [ ]:
x.grad #this is derivative value

tensor(10.)

In [ ]:
#another one
x = torch.tensor(5.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)

In [ ]:
print(x)
print(y)
print(z)

tensor(5., requires_grad=True)
tensor(25., grad_fn=<PowBackward0>)
tensor(-0.1324, grad_fn=<SinBackward0>)


In [ ]:
z.backward() #backtrack

In [ ]:
x.grad

tensor(9.9120)

In [ ]:
#vector
x = torch.tensor([2.0, 5.0, 9.0], requires_grad=True)
x

tensor([2., 5., 9.], requires_grad=True)

In [ ]:
y = (x**2).mean()
y

tensor(36.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad #we compute the three

tensor([1.3333, 3.3333, 6.0000])

In [ ]:
x.grad.zero_() #this ensure the gradient doesnot accumulate in the loop process

tensor([0., 0., 0.])

In [ ]:
#closing the gradient tracking
x.requires_grad_(False) #underline will make inplace change

tensor([2., 5., 9.])

In [ ]:
#using detach function
z = x.detach()
z

tensor([2., 5., 9.])

In [ ]:
#using no grad function
x = torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [ ]:
with torch.no_grad():
  y=x**2

In [ ]:
y

tensor(25.)

In [ ]:
y.backward() #returns error

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn