<a href="https://colab.research.google.com/github/NishanRegmi/Pytorch/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. CPU is using")

GPU not available. CPU is using


**Creating Tensor**

In [ ]:
#using empty
x = torch.empty(2, 3)
print(x)

tensor([[2.3397e-25, 0.0000e+00, 9.3205e-09],
        [6.4108e-10, 6.2353e-10, 1.3567e-19]])


In [ ]:
#checking type
type(x)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2, 3) #generate random value between 0 - 1

tensor([[0.9089, 0.4287, 0.4190],
        [0.5053, 0.9563, 0.7534]])

In [ ]:
#use of seed
torch.manual_seed(5) #for reproducibility
torch.rand(2, 3)

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [ ]:
#creating tensor using torch
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#using arange
torch.arange(0, 5)

tensor([0, 2, 4])

In [ ]:
#using linspace
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
#identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#using full
torch.full((3, 3), 4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

**Tensor shape**

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#creating new tensor having the same size of x
print(torch.empty_like(x))
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[      378787824,       379746704,        11653544],
        [       10846432, 135786017618032, 135786018378624]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [ ]:
torch.rand_like(x) #it returns error because rand function generate value between 0-1 but our original x has value in int.
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1644, 0.7379, 0.0333],
        [0.9942, 0.6064, 0.5646]])

**Tensor Datatypes**

In [ ]:
#find dtype
print(x)
print(x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [ ]:
#specify dtype while creating
torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.int32)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [ ]:
#covert existing tensor into another dtype
print(x)
x.to(dtype=torch.float32)

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathematical Operation**

1. Scaler operation

In [ ]:
x = torch.rand(2, 2)
print(x)

tensor([[0.0724, 0.6593],
        [0.7150, 0.5793]])


In [ ]:
#addition
x+2

#subtraction
x-2

#multiplication
x*2

#division
x/2

#int division
(x*100)//2

#mod
((x*100)//2)%2

#power
x**2

tensor([[0.0052, 0.4347],
        [0.5112, 0.3356]])

2. Element wise operation

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [ ]:
print(a)
print(b)

tensor([[0.9809, 0.6502, 0.0566],
        [0.9201, 0.6698, 0.2615]])
tensor([[0.0407, 0.7850, 0.9752],
        [0.0903, 0.5273, 0.6794]])


In [ ]:
#addition
a+b

#substraction
a-b

#multiplication
a*b

#division
a/b

#power
a**b

#mod
a%b

tensor([[0.0038, 0.6502, 0.0566],
        [0.0167, 0.1424, 0.2615]])

In [ ]:
c = torch.tensor([1, -2, -3, 4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.negative(c)

tensor([-1,  2,  3, -4])

In [ ]:
d = torch.tensor([1.8, 2.2, 3.5, 5.6])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 6.])

In [ ]:
#ceiling
torch.ceil(d)

tensor([2., 3., 4., 6.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 5.])

In [ ]:
#clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.2000, 3.5000, 4.0000])

3. Reduction

In [ ]:
e = torch.randint(2, 10, (2, 3))
print(e)

tensor([[6, 3, 5],
        [5, 9, 4]])


In [ ]:
#sum
torch.sum(e)

#sum along column
torch.sum(e, dim=0) #0 means column

#sum row wise
torch.sum(e, dim=1) #1 means row


tensor([14, 18])

In [ ]:
f = torch.rand(2, 3)
f

tensor([[0.1600, 0.9041, 0.5557],
        [0.7280, 0.8709, 0.1760]])

In [ ]:
#mean
torch.mean(f)

#mean along row
torch.mean(f, dim=1)

#mean along column
torch.mean(f, dim=0)

#minimum
torch.min(f)

#maximum
torch.max(f)

#std
torch.std(f)

#variance
torch.var(f)

#product
torch.prod(f)

#argmax
torch.argmax(f) #return index of max value

#argmin
torch.argmin(f) #return index of min value

tensor(0)

4. Matrix operation

In [ ]:
m = torch.randint(0, 10, size=(2, 3))
n = torch.randint(0, 10, size = (3, 2))

print(m)
print(n)

tensor([[5, 3, 9],
        [7, 9, 4]])
tensor([[2, 4],
        [0, 7],
        [7, 4]])


In [ ]:
#matrix multiplication
torch.matmul(m, n)

tensor([[ 73,  77],
        [ 42, 107]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

#dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
#transpose
z = torch.tensor([[5, 3, 9],
        [7, 9, 4]])
print(z)
print(z.shape)

tensor([[5, 3, 9],
        [7, 9, 4]])
torch.Size([2, 3])


In [ ]:
torch.transpose(z, 0, 1)

tensor([[5, 7],
        [3, 9],
        [9, 4]])

In [ ]:
h = torch.randint(0, 10, size=(3, 3), dtype=torch.float32)
h

tensor([[6., 4., 8.],
        [1., 9., 6.],
        [5., 4., 2.]])

In [ ]:
#determinant
torch.det(h)

tensor(-252.)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ 0.0238, -0.0952,  0.1905],
        [-0.1111,  0.1111,  0.1111],
        [ 0.1627,  0.0159, -0.1984]])

Special function

In [ ]:
y = torch.randint(0, 10, size=(2, 3), dtype=torch.float32)
y

tensor([[0., 0., 5.],
        [1., 8., 8.]])

In [ ]:
#log
torch.log(y)

#exp
torch.exp(y)

#sqrt
torch.sqrt(y)

#sigmoid
torch.sigmoid(y)

#softmax
torch.softmax(y, dim=0)

#relu
torch.relu(y)

tensor([[0., 0., 5.],
        [1., 8., 8.]])

Inplace operation

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.2000, 0.0926, 0.9684],
        [0.2989, 0.3341, 0.5623]])
tensor([[0.7826, 0.5385, 0.3656],
        [0.5424, 0.2409, 0.1363]])


In [ ]:
a+b #it save value in another space that cause the use of more space

tensor([[0.9826, 0.6310, 1.3341],
        [0.8413, 0.5751, 0.6986]])

In [ ]:
a.add_(b) #store value on a

tensor([[0.9826, 0.6310, 1.3341],
        [0.8413, 0.5751, 0.6986]])

In [ ]:
print(a)

tensor([[0.9826, 0.6310, 1.3341],
        [0.8413, 0.5751, 0.6986]])


Copying tensor

In [ ]:
a = torch.rand(2, 3)
a

tensor([[0.6302, 0.5527, 0.7484],
        [0.3143, 0.0058, 0.3759]])

In [ ]:
b = a
print(b)

tensor([[0.6302, 0.5527, 0.7484],
        [0.3143, 0.0058, 0.3759]])


In [ ]:
#if i change something in a, change also reflect in b
a[0][0] = 0

In [ ]:
print(a)
print(b) #this might be the problem in some case

tensor([[0.0000, 0.5527, 0.7484],
        [0.3143, 0.0058, 0.3759]])
tensor([[0.0000, 0.5527, 0.7484],
        [0.3143, 0.0058, 0.3759]])


In [ ]:
#best way of copying
b = a.clone() #copying this way won't reflect changes if changes occur in original tensor

**Tensor Operation in GPU**

In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. CPU is using")

GPU is available
using GPU: Tesla T4


In [ ]:
device = torch.device('cuda')

In [ ]:
#creating new tensor on gpu
torch.rand(2, 3, device=device)

tensor([[0.4756, 0.6801, 0.5096],
        [0.4468, 0.9934, 0.7406]], device='cuda:0')

In [ ]:
a = torch.rand(2, 3)
a

tensor([[0.1886, 0.3879, 0.1117],
        [0.9325, 0.8225, 0.0338]])

In [ ]:
#moving existing tensor to gpu
b = a.to(device)
print(b)

tensor([[0.1886, 0.3879, 0.1117],
        [0.9325, 0.8225, 0.0338]], device='cuda:0')


In [ ]:
import torch
import time

matrix1 = torch.randn(10000, 10000)
matrix2 = torch.randn(10000, 10000)

#measure time on cpu
start = time.time()
result_cpu = torch.matmul(matrix1, matrix2)
cpu_time = time.time()-start

print(f"Time taken on cpu: {cpu_time:.4f} seconds")

#measure time on gpu
matrix1_gpu = matrix1.to(device)
matrix2_gpu = matrix2.to(device)

start_gpu = time.time()
result_gpu = torch.matmul(matrix1_gpu, matrix2_gpu)
torch.cuda.synchronize()
gpu_time = time.time()-start_gpu

print(f"Time taken on gpu: {gpu_time:.4f} seconds")

print("\n Speedup (cpu time / gpu time)", cpu_time/gpu_time)

Time taken on cpu: 15.4362 seconds
Time taken on gpu: 0.5555 seconds

 Speedup (cpu time / gpu time) 27.78711502145923


Reshaping tensors

In [ ]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])